//Rename this file to env.js
export const GOOGLE_API_KEY = "YOUR_GOOGLE_API_KEY";
export const EXPO_PUBLIC_GEMINI_API = "YOUR_EXPO_PUBLIC_GEMINI_API";
export const WEATHER_API_KEY = "YOUR_WEATHER_API_KEY"; //https://api.weatherapi.com/

export const FIREBASE_CONFIG = {
  API_KEY: "YOUR_FIREBASE_API_KEY",
  AUTH_DOMAIN: "YOUR_FIREBASE_AUTH_DOMAIN",
  PROJECT_ID: "YOUR_FIREBASE_PROJECT_ID",
  STORAGE_BUCKET: "YOUR_FIREBASE_STORAGE_BUCKET",
  MESSAGING_SENDER_ID: "YOUR_FIREBASE_MESSAGING_SENDER_ID",
  APP_ID: "YOUR_FIREBASE_APP_ID",
};
